import { ViewStyle } from 'react-native';
declare const setSafeBounceHeight: (height: number) => void;
declare const getSafeBounceHeight: () => number;
declare const getDefaultHeaderHeight: (isLandscape: boolean) => 32 | 44 | 56 | 0;
declare const disableExpoTranslucentStatusBar: () => void;
declare const getStatusBarHeight: (isLandscape: boolean) => number;
declare const getNavigationHeight: (isLandscape: boolean, headerHeight: number) => number;
declare const getScrollIndicatorInsetTop: (isLandscape: boolean, headerHeight: number) => number;
declare const getElevationStyle: (elevation: number) => ViewStyle;
export { setSafeBounceHeight, getSafeBounceHeight, getDefaultHeaderHeight, getNavigationHeight, getStatusBarHeight, getScrollIndicatorInsetTop, disableExpoTranslucentStatusBar, getElevationStyle, };
